package common

type MarketDataSnapshot struct {
	ServerID string `json:"server_id"`
	ConID    int    `json:"conid"`
	Updated  int    `json:"_updated"`
	MarketDataFields
}

type MarketDataFields struct {
	LastPrice                string `json:"31"`
	Symbol                   string `json:"55"`
	Text                     string `json:"58"`
	High                     string `json:"70"`
	Low                      string `json:"71"`
	MarketValue              string `json:"73"`
	AvgPrice                 string `json:"74"`
	UnrealizedPnL            string `json:"75"`
	FormattedPosition        string `json:"76"`
	FormattedUnrealPnL       string `json:"77"`
	DailyPnL                 string `json:"78"`
	RealizedPnL              string `json:"79"`
	UnrealizedPnLPercent     string `json:"80"`
	Change                   string `json:"82"`
	ChangePercent            string `json:"83"`
	BidPrice                 string `json:"84"`
	AskSize                  string `json:"85"`
	AskPrice                 string `json:"86"`
	Volume                   string `json:"87"`
	RawVolume                string `json:"87_raw (deprecated)"`
	BidSize                  string `json:"88"`
	Exchange                 string `json:"6004"`
	ConIDIBKR                int    `json:"6008"`
	SecType                  string `json:"6070"`
	Months                   string `json:"6072"`
	RegularExpiry            string `json:"6073"`
	MarketDataDeliveryMethod string `json:"6509"`
	CompanyName              string `json:"7051"`
	AskExchange              string `json:"7057"`
	LastExchange             string `json:"7058"`
	LastSize                 string `json:"7059"`
	BidExchange              string `json:"7068"`
	ImpliedVolHistVolPercent string `json:"7084"`
	PutCallInterest          string `json:"7085"`
	PutCallVolume            string `json:"7086"`
	HistVolPercent           string `json:"7087"`
	HistVolClosePercent      string `json:"7088"`
	OptionVolume             string `json:"7089"`
	ConIDExchange            string `json:"7094"`
	CanBeTraded              string `json:"7184"`
	ContractDescription      string `json:"7219"`
	ContractDescription2     string `json:"7220"`
	ListingExchange          string `json:"7221"`
	Industry                 string `json:"7280"`
	Category                 string `json:"7281"`
	AverageVolume            string `json:"7282"`
	OptionImpliedVolPercent  string `json:"7283"`
	HistoricVolume30d        string `json:"7284"`
	PutCallRatio             string `json:"7285"`
	DividendAmount           string `json:"7286"`
	DividendYieldPercent     string `json:"7287"`
	DividendExDate           string `json:"7288"`
	MarketCap                string `json:"7289"`
	PE                       string `json:"7290"`
	EPS                      string `json:"7291"`
	CostBasis                string `json:"7292"`
	WeekHigh                 string `json:"7293"`
	WeekLow                  string `json:"7294"`
	Open                     string `json:"7295"`
	Close                    string `json:"7296"`
	Delta                    string `json:"7308"`
	Gamma                    string `json:"7309"`
	Theta                    string `json:"7310"`
	Vega                     string `json:"7311"`
	OptVolumeChangePercent   string `json:"7607"`
	ImpliedVolPercent        string `json:"7633"`
	Mark                     string `json:"7635"`
	ShortableShares          string `json:"7636"`
	FeeRate                  string `json:"7637"`
	OptionOpenInterest       string `json:"7638"`
	MarkValuePercent         string `json:"7639"`
	Shortable                string `json:"7644"`
	MorningstarRating        string `json:"7655"`
	Dividends                string `json:"7671"`
	DividendsTTM             string `json:"7672"`
	EMA200                   string `json:"7674"`
	EMA100                   string `json:"7675"`
	EMA50                    string `json:"7676"`
	EMA20                    string `json:"7677"`
	PriceEMA200              string `json:"7678"`
	PriceEMA100              string `json:"7679"`
	PriceEMA50               string `json:"7680"`
	PriceEMA20               string `json:"7681"`
	ChangeSinceOpen          string `json:"7682"`
	UpcomingEvent            string `json:"7683"`
	UpcomingEventDate        string `json:"7684"`
	UpcomingAnalystMeeting   string `json:"7685"`
	UpcomingEarnings         string `json:"7686"`
	UpcomingMiscEvent        string `json:"7687"`
	RecentAnalystMeeting     string `json:"7688"`
	RecentEarnings           string `json:"7689"`
	RecentMiscEvent          string `json:"7690"`
	ProbabilityMaxReturn     string `json:"7694"`
	BreakEven                string `json:"7695"`
	SPXDelta                 string `json:"7696"`
	FuturesOpenInterest      string `json:"7697"`
	LastYield                string `json:"7698"`
	BidYield                 string `json:"7699"`
	ProbabilityMaxLoss       string `json:"7702"`
	ProfitProbability        string `json:"7703"`
	OrganizationType         string `json:"7704"`
	DebtClass                string `json:"7705"`
	Ratings                  string `json:"7706"`
	BondStateCode            string `json:"7707"`
	BondType                 string `json:"7708"`
	LastTradingDate          string `json:"7714"`
	IssueDate                string `json:"7715"`
	Beta                     string `json:"7718"`
	AskYield                 string `json:"7720"`
	PriorClose               string `json:"7741"`
	VolumeLong               string `json:"7762"`
	HasTradingPermissions    string `json:"7768"`
	DailyPnLRaw              string `json:"7920"`
	CostBasisRaw             string `json:"7921"`
}

type MarketDataHistory struct {
	Symbol             string `json:"symbol"`
	Text               string `json:"text"`
	PriceFactor        int    `json:"priceFactor"`
	StartTime          string `json:"startTime"`
	High               string `json:"high"`
	Low                string `json:"low"`
	TimePeriod         string `json:"timePeriod"`
	BarLength          int    `json:"barLength"`
	MDAvailability     string `json:"mdAvailability"`
	MktDataDelay       int    `json:"mktDataDelay"`
	OutsideRTH         bool   `json:"outsideRth"`
	TradingDayDuration int    `json:"tradingDayDuration"`
	VolumeFactor       int    `json:"volumeFactor"`
	PriceDisplayRule   int    `json:"priceDisplayRule"`
	PriceDisplayValue  string `json:"priceDisplayValue"`
	NegativeCapable    bool   `json:"negativeCapable"`
	MessageVersion     int    `json:"messageVersion"`
	Data               []struct {
		Open      int `json:"o"`
		Close     int `json:"c"`
		High      int `json:"h"`
		Low       int `json:"l"`
		Volume    int `json:"v"`
		Timestamp int `json:"t"`
	} `json:"data"`
	Points     int `json:"points"`
	TravelTime int `json:"travelTime"`
}
